spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/Getway
          jwk-set-uri: http://localhost:8085/realms/Getway/protocol/openid-connect/certs